apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: team-researchops
  name: skup
  namespace: team-researchops

spec:
  ingresses:
    - https://skup.ansatt.nav.no
  image: {{image}}
  port: 3000
  accessPolicy:
    outbound:
      rules:
        - application: skup-backend
  resources:
    limits:
      cpu: 200m
      memory: 32Mi
    requests:
      cpu: 100m
      memory: 32Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      autoLogin: true
      enabled: true