import type { Metadata } from "next";

import "@navikt/ds-css";
import "./tailwind.css"

import Header from "@/app/components/header";
import Footer from "@/app/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="no">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
